module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/favicon.ico (static in ecmascript, tag client)", ((__turbopack_context__) => {

__turbopack_context__.v("/_next/static/media/favicon.2vob68tjqpejf.ico" + (globalThis["NEXT_CLIENT_ASSET_SUFFIX"] || ''));}),
"[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$favicon$2e$ico__$28$static__in__ecmascript$2c$__tag__client$29$__ = __turbopack_context__.i("[project]/src/app/favicon.ico (static in ecmascript, tag client)");
;
const __TURBOPACK__default__export__ = {
    src: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$favicon$2e$ico__$28$static__in__ecmascript$2c$__tag__client$29$__["default"],
    width: 256,
    height: 256
};
}),
"[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CaregiverAuthPanel",
    ()=>CaregiverAuthPanel
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CaregiverAuthPanel = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CaregiverAuthPanel() from the server but CaregiverAuthPanel is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/auth/caregiver-auth-panel.tsx <module evaluation>", "CaregiverAuthPanel");
}),
"[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CaregiverAuthPanel",
    ()=>CaregiverAuthPanel
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CaregiverAuthPanel = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CaregiverAuthPanel() from the server but CaregiverAuthPanel is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/auth/caregiver-auth-panel.tsx", "CaregiverAuthPanel");
}),
"[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$auth$2f$caregiver$2d$auth$2d$panel$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$auth$2f$caregiver$2d$auth$2d$panel$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$auth$2f$caregiver$2d$auth$2d$panel$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/brand-mark.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "BrandMark",
    ()=>BrandMark
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$Heartbeat$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@phosphor-icons/react/dist/ssr/Heartbeat.es.js [app-rsc] (ecmascript)");
;
;
function BrandMark({ compact = false }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
        className: `brand ${compact ? "brand-compact" : ""}`.trim(),
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                className: "brand-symbol",
                "aria-hidden": "true",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$Heartbeat$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Heartbeat"], {
                    size: compact ? 19 : 22,
                    weight: "bold"
                }, void 0, false, {
                    fileName: "[project]/src/components/brand-mark.tsx",
                    lineNumber: 7,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/src/components/brand-mark.tsx",
                lineNumber: 6,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                children: "ChroniCare"
            }, void 0, false, {
                fileName: "[project]/src/components/brand-mark.tsx",
                lineNumber: 9,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/src/components/brand-mark.tsx",
        lineNumber: 5,
        columnNumber: 5
    }, this);
}
}),
"[externals]/node:crypto [external] (node:crypto, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:crypto", () => require("node:crypto"));

module.exports = mod;
}),
"[project]/src/lib/env/errors.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "EnvironmentConfigurationError",
    ()=>EnvironmentConfigurationError
]);
class EnvironmentConfigurationError extends Error {
    keys;
    scope;
    constructor(scope, keys){
        const uniqueKeys = [
            ...new Set(keys)
        ].sort();
        super(`Invalid or missing environment configuration for ${scope}: ${uniqueKeys.join(", ")}.`);
        this.name = "EnvironmentConfigurationError";
        this.scope = scope;
        this.keys = uniqueKeys;
    }
}
}),
"[project]/src/lib/env/validation.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "inspect",
    ()=>inspect,
    "nonEmpty",
    ()=>nonEmpty,
    "normalizeRuntimeEnvironment",
    ()=>normalizeRuntimeEnvironment,
    "parseOrThrow",
    ()=>parseOrThrow,
    "webUrl",
    ()=>webUrl
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__ = __turbopack_context__.i("[project]/node_modules/zod/v4/classic/external.js [app-rsc] (ecmascript) <export * as z>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$errors$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/errors.ts [app-rsc] (ecmascript)");
;
;
const nonEmpty = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().trim().min(1);
function webUrl(runtime) {
    return __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].url().refine((value)=>{
        if (!URL.canParse(value)) {
            return false;
        }
        const protocol = new URL(value).protocol;
        return protocol === "https:" || runtime !== "production" && protocol === "http:";
    }, "Must use HTTPS outside local development");
}
function invalidKeys(error) {
    return error.issues.map((issue)=>String(issue.path[0] ?? "unknown"));
}
function parseOrThrow(schema, source, scope) {
    const result = schema.safeParse(source);
    if (!result.success) {
        throw new __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$errors$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["EnvironmentConfigurationError"](scope, invalidKeys(result.error));
    }
    return result.data;
}
function inspect(schema, source) {
    const result = schema.safeParse(source);
    if (result.success) {
        return {
            configured: true,
            value: result.data
        };
    }
    return {
        configured: false,
        invalidKeys: [
            ...new Set(invalidKeys(result.error))
        ].sort()
    };
}
function normalizeRuntimeEnvironment(value) {
    if (value === "production" || value === "test") {
        return value;
    }
    return "development";
}
}),
"[project]/src/lib/env/public-schema.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PUBLIC_ENV_KEYS",
    ()=>PUBLIC_ENV_KEYS,
    "parsePublicEnv",
    ()=>parsePublicEnv
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__ = __turbopack_context__.i("[project]/node_modules/zod/v4/classic/external.js [app-rsc] (ecmascript) <export * as z>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/validation.ts [app-rsc] (ecmascript)");
;
;
const PUBLIC_ENV_KEYS = [
    "NEXT_PUBLIC_APP_URL",
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
];
function parsePublicEnv(source, runtime = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeRuntimeEnvironment"])(source.NODE_ENV)) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        NEXT_PUBLIC_APP_URL: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["webUrl"])(runtime),
        NEXT_PUBLIC_SUPABASE_URL: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["webUrl"])(runtime),
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"]
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseOrThrow"])(schema, source, "public browser env");
}
}),
"[project]/src/lib/env/public.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getPublicEnv",
    ()=>getPublicEnv
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$public$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/public-schema.ts [app-rsc] (ecmascript)");
;
function getPublicEnv() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$public$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parsePublicEnv"])({
        NODE_ENV: ("TURBOPACK compile-time value", "development"),
        NEXT_PUBLIC_APP_URL: ("TURBOPACK compile-time value", "http://localhost:3201"),
        NEXT_PUBLIC_SUPABASE_URL: ("TURBOPACK compile-time value", "https://eulfdpwebhvalqsljnea.supabase.co"),
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ("TURBOPACK compile-time value", "sb_publishable_bEYOOqS7q6cmL8apv1HKIw_mYwY9QS1")
    });
}
}),
"[project]/src/lib/supabase/server.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "createSupabaseServerClient",
    ()=>createSupabaseServerClient
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$ssr$2f$dist$2f$module$2f$createServerClient$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@supabase/ssr/dist/module/createServerClient.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$public$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/public.ts [app-rsc] (ecmascript)");
;
;
;
;
async function createSupabaseServerClient() {
    const env = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$public$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPublicEnv"])();
    const cookieStore = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cookies"])();
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$ssr$2f$dist$2f$module$2f$createServerClient$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createServerClient"])(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, {
        cookies: {
            getAll: ()=>cookieStore.getAll(),
            setAll: (cookiesToSet)=>{
                cookiesToSet.forEach(({ name, value, options })=>cookieStore.set(name, value, options));
            }
        }
    });
}
}),
"[project]/src/lib/onboarding/schemas.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "caregiverRegistrationSchema",
    ()=>caregiverRegistrationSchema,
    "ownerOnboardingDefaultsFromMetadata",
    ()=>ownerOnboardingDefaultsFromMetadata,
    "ownerOnboardingInputFromMetadata",
    ()=>ownerOnboardingInputFromMetadata,
    "ownerOnboardingSchema",
    ()=>ownerOnboardingSchema
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__ = __turbopack_context__.i("[project]/node_modules/zod/v4/classic/external.js [app-rsc] (ecmascript) <export * as z>");
;
const ownerOnboardingSchema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
    displayName: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().trim().min(2).max(120),
    careCircleName: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().trim().min(2).max(120)
}).strict();
const caregiverRegistrationSchema = ownerOnboardingSchema.extend({
    email: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].email().max(254),
    password: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().min(8).max(72),
    passwordConfirmation: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().min(8).max(72)
}).refine((value)=>value.password === value.passwordConfirmation, {
    path: [
        "passwordConfirmation"
    ],
    message: "PASSWORD_MISMATCH"
});
function ownerOnboardingDefaultsFromMetadata(metadata) {
    if (typeof metadata !== "object" || metadata === null) return {};
    const values = metadata;
    const text = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().trim().min(2).max(120);
    const displayName = text.safeParse(values["display_name"]);
    const careCircleName = text.safeParse(values["care_circle_name"]);
    return {
        ...displayName.success ? {
            displayName: displayName.data
        } : {},
        ...careCircleName.success ? {
            careCircleName: careCircleName.data
        } : {}
    };
}
function ownerOnboardingInputFromMetadata(metadata) {
    const result = ownerOnboardingSchema.safeParse(ownerOnboardingDefaultsFromMetadata(metadata));
    return result.success ? result.data : null;
}
}),
"[project]/src/lib/auth/caregiver.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CaregiverAuthError",
    ()=>CaregiverAuthError,
    "requireOwner",
    ()=>requireOwner,
    "resolveAuthenticatedCaregiverUser",
    ()=>resolveAuthenticatedCaregiverUser,
    "resolveCaregiverAuthContext",
    ()=>resolveCaregiverAuthContext
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/supabase/server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$onboarding$2f$schemas$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/onboarding/schemas.ts [app-rsc] (ecmascript)");
;
;
;
class CaregiverAuthError extends Error {
    code;
    onboardingDefaults;
    constructor(code, onboardingDefaults){
        super(code), this.code = code, this.onboardingDefaults = onboardingDefaults;
        this.name = "CaregiverAuthError";
    }
}
async function resolveAuthenticatedCaregiverUser(dependencies = {}) {
    const supabase = dependencies.supabase ?? await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createSupabaseServerClient"])();
    const { data, error } = await supabase.auth.getUser();
    if (error || !data.user) throw new CaregiverAuthError("UNAUTHENTICATED");
    const onboardingDefaults = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$onboarding$2f$schemas$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ownerOnboardingDefaultsFromMetadata"])(data.user.user_metadata);
    return {
        id: data.user.id,
        ...Object.keys(onboardingDefaults).length > 0 ? {
            onboardingDefaults
        } : {}
    };
}
async function resolveCaregiverAuthContext(dependencies = {}) {
    const authUser = await resolveAuthenticatedCaregiverUser({
        supabase: dependencies.supabase
    });
    const db = dependencies.db ?? (await __turbopack_context__.A("[project]/src/lib/db/client.ts [app-rsc] (ecmascript, async loader)")).prisma;
    const membership = await db.careCircleMember.findFirst({
        where: {
            userId: authUser.id,
            status: "ACTIVE",
            careCircle: {
                isActive: true
            }
        },
        select: {
            careCircleId: true,
            role: true,
            user: {
                select: {
                    displayName: true
                }
            }
        }
    });
    if (!membership) {
        const applicationUser = await db.user.findUnique({
            where: {
                id: authUser.id
            },
            select: {
                id: true
            }
        });
        throw new CaregiverAuthError(applicationUser ? "FORBIDDEN" : "ONBOARDING_REQUIRED", applicationUser ? undefined : authUser.onboardingDefaults);
    }
    return {
        actorType: "CAREGIVER",
        user: {
            id: authUser.id,
            displayName: membership.user.displayName
        },
        membership: {
            careCircleId: membership.careCircleId,
            role: membership.role
        }
    };
}
function requireOwner(context) {
    if (!context) {
        throw new CaregiverAuthError("UNAUTHENTICATED");
    }
    if (context.membership.role !== "OWNER") {
        throw new CaregiverAuthError("FORBIDDEN");
    }
    return context;
}
}),
"[project]/src/lib/env/server-schema.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SERVER_ONLY_ENV_KEYS",
    ()=>SERVER_ONLY_ENV_KEYS,
    "inspectAzureDocumentIntelligenceEnv",
    ()=>inspectAzureDocumentIntelligenceEnv,
    "inspectAzureOpenAIEnv",
    ()=>inspectAzureOpenAIEnv,
    "inspectSupabaseAdminEnv",
    ()=>inspectSupabaseAdminEnv,
    "parseCoreServerEnv",
    ()=>parseCoreServerEnv,
    "parseProviderFlags",
    ()=>parseProviderFlags
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__ = __turbopack_context__.i("[project]/node_modules/zod/v4/classic/external.js [app-rsc] (ecmascript) <export * as z>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/validation.ts [app-rsc] (ecmascript)");
;
;
const postgresUrl = __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"].refine((value)=>{
    try {
        const protocol = new URL(value).protocol;
        return protocol === "postgres:" || protocol === "postgresql:";
    } catch  {
        return false;
    }
}, "Must be a PostgreSQL connection URL");
const fallbackMode = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].enum([
    "disabled",
    "synthetic-demo"
]);
const booleanString = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].enum([
    "true",
    "false"
]).transform((value)=>value === "true");
const SERVER_ONLY_ENV_KEYS = [
    "SUPABASE_SERVICE_ROLE_KEY",
    "DATABASE_URL",
    "DIRECT_URL",
    "PATIENT_SESSION_SECRET",
    "AZURE_OPENAI_ENDPOINT",
    "AZURE_OPENAI_API_KEY",
    "AZURE_OPENAI_API_VERSION",
    "AZURE_OPENAI_DEPLOYMENT",
    "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT",
    "AZURE_DOCUMENT_INTELLIGENCE_KEY",
    "AZURE_DOCUMENT_INTELLIGENCE_MODEL"
];
function parseCoreServerEnv(source) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        DATABASE_URL: postgresUrl,
        DIRECT_URL: postgresUrl,
        PATIENT_SESSION_SECRET: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].string().min(32)
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseOrThrow"])(schema, source, "core server env");
}
function inspectSupabaseAdminEnv(source, runtime = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeRuntimeEnvironment"])(source.NODE_ENV)) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        NEXT_PUBLIC_SUPABASE_URL: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["webUrl"])(runtime),
        SUPABASE_SERVICE_ROLE_KEY: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"]
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspect"])(schema, source);
}
function inspectAzureOpenAIEnv(source, runtime = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeRuntimeEnvironment"])(source.NODE_ENV)) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        AZURE_OPENAI_ENDPOINT: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["webUrl"])(runtime),
        AZURE_OPENAI_API_KEY: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"],
        AZURE_OPENAI_API_VERSION: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"],
        AZURE_OPENAI_DEPLOYMENT: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"]
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspect"])(schema, source);
}
function inspectAzureDocumentIntelligenceEnv(source, runtime = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["normalizeRuntimeEnvironment"])(source.NODE_ENV)) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["webUrl"])(runtime),
        AZURE_DOCUMENT_INTELLIGENCE_KEY: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"],
        AZURE_DOCUMENT_INTELLIGENCE_MODEL: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["nonEmpty"]
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspect"])(schema, source);
}
function parseProviderFlags(source) {
    const schema = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].object({
        OCR_FALLBACK_MODE: fallbackMode.default("disabled"),
        OCR_MAX_FILE_BYTES: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].coerce.number().int().min(1_048_576).max(5_242_880).default(5_242_880),
        OCR_MAX_PAGES: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$zod$2f$v4$2f$classic$2f$external$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__$2a$__as__z$3e$__["z"].coerce.number().int().min(1).max(3).default(3),
        SOS_AUDIO_ENABLED_BY_DEFAULT: booleanString.default(false)
    });
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$validation$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseOrThrow"])(schema, source, "provider flags");
}
}),
"[project]/src/lib/env/server.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getAzureDocumentIntelligenceEnv",
    ()=>getAzureDocumentIntelligenceEnv,
    "getAzureOpenAIEnv",
    ()=>getAzureOpenAIEnv,
    "getCoreServerEnv",
    ()=>getCoreServerEnv,
    "getProviderFlags",
    ()=>getProviderFlags,
    "getSupabaseAdminEnv",
    ()=>getSupabaseAdminEnv
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/server-schema.ts [app-rsc] (ecmascript)");
;
;
function getCoreServerEnv() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseCoreServerEnv"])(process.env);
}
function getSupabaseAdminEnv() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspectSupabaseAdminEnv"])(process.env);
}
function getAzureOpenAIEnv() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspectAzureOpenAIEnv"])(process.env);
}
function getAzureDocumentIntelligenceEnv() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["inspectAzureDocumentIntelligenceEnv"])(process.env);
}
function getProviderFlags() {
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2d$schema$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["parseProviderFlags"])(process.env);
}
}),
"[project]/src/lib/auth/patient.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PATIENT_SESSION_COOKIE",
    ()=>PATIENT_SESSION_COOKIE,
    "PATIENT_SESSION_MAX_AGE_SECONDS",
    ()=>PATIENT_SESSION_MAX_AGE_SECONDS,
    "PatientAuthError",
    ()=>PatientAuthError,
    "authenticatePatientCode",
    ()=>authenticatePatientCode,
    "requireBoundPatientProfile",
    ()=>requireBoundPatientProfile,
    "resolveAuthContext",
    ()=>resolveAuthContext,
    "resolvePatientAuthContext",
    ()=>resolvePatientAuthContext,
    "revokePatientSession",
    ()=>revokePatientSession,
    "verifyArgon2id",
    ()=>verifyArgon2id
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/node:crypto [external] (node:crypto, cjs)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$caregiver$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/auth/caregiver.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/env/server.ts [app-rsc] (ecmascript)");
;
;
;
;
const PATIENT_SESSION_COOKIE = "chronicare_patient_session";
const PATIENT_SESSION_MAX_AGE_SECONDS = 8 * 60 * 60;
class PatientAuthError extends Error {
    code;
    constructor(code){
        super(code), this.code = code;
        this.name = "PatientAuthError";
    }
}
const argon2 = __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__.argon2;
async function verifyArgon2id(value, encodedHash) {
    const match = encodedHash.match(/^\$argon2id\$v=19\$m=(\d+),t=(\d+),p=(\d+)\$([A-Za-z0-9+/]+={0,2})\$([A-Za-z0-9+/]+={0,2})$/);
    if (!match) return false;
    const [, memoryText, passesText, parallelismText, saltText, hashText] = match;
    const memory = Number(memoryText);
    const passes = Number(passesText);
    const parallelism = Number(parallelismText);
    const nonce = Buffer.from(saltText, "base64");
    const expected = Buffer.from(hashText, "base64");
    if (!Number.isInteger(memory) || !Number.isInteger(passes) || !Number.isInteger(parallelism) || memory < 8 || memory > 262_144 || passes < 1 || passes > 10 || parallelism < 1 || parallelism > 16 || nonce.length < 8 || expected.length < 16 || expected.length > 64) {
        return false;
    }
    try {
        const actual = await new Promise((resolve, reject)=>{
            argon2("argon2id", {
                message: Buffer.from(value),
                nonce,
                parallelism,
                tagLength: expected.length,
                memory,
                passes
            }, (error, result)=>{
                if (error || !result) reject(error ?? new Error("Argon2 failed"));
                else resolve(result);
            });
        });
        return __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__.timingSafeEqual(actual, expected);
    } catch  {
        return false;
    }
}
function sessionTokenHash(token, secret) {
    return __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__.createHmac("sha256", secret).update(token).digest("hex");
}
async function readPatientSessionCookie() {
    const { cookies } = await __turbopack_context__.A("[project]/node_modules/next/headers.js [app-rsc] (ecmascript, async loader)");
    return (await cookies()).get(PATIENT_SESSION_COOKIE)?.value ?? null;
}
const loginAttempts = new Map();
const LOGIN_WINDOW_MS = 15 * 60 * 1_000;
// ponytail: process-local limiter fits the single demo server; use a shared store before multi-instance deploy.
function loginAttemptKey(fingerprint, secret) {
    return __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__.createHmac("sha256", secret).update(fingerprint).digest("hex");
}
function requireLoginAttemptAllowed(key, now) {
    const attempt = loginAttempts.get(key);
    if (attempt && attempt.lockedUntil > now) {
        throw new PatientAuthError("RATE_LIMITED");
    }
    if (attempt && now - attempt.windowStartedAt >= LOGIN_WINDOW_MS) {
        loginAttempts.delete(key);
    }
}
function recordFailedLogin(key, now) {
    const current = loginAttempts.get(key);
    const count = current ? current.count + 1 : 1;
    const windowStartedAt = current?.windowStartedAt ?? now;
    const lockedUntil = count >= 5 ? now + LOGIN_WINDOW_MS : 0;
    loginAttempts.set(key, {
        count,
        windowStartedAt,
        lockedUntil
    });
    if (lockedUntil) throw new PatientAuthError("RATE_LIMITED");
}
async function authenticatePatientCode(input, dependencies = {}) {
    const db = dependencies.db ?? (await __turbopack_context__.A("[project]/src/lib/db/client.ts [app-rsc] (ecmascript, async loader)")).prisma;
    const secret = dependencies.secret ?? (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getCoreServerEnv"])().PATIENT_SESSION_SECRET;
    const now = input.now ?? new Date();
    const attemptKey = loginAttemptKey(input.fingerprint, secret);
    requireLoginAttemptAllowed(attemptKey, now.getTime());
    // ponytail: at most two demo profiles make a hash scan smaller than a lookup-prefix schema change.
    const candidates = await db.patientAccessCode.findMany({
        where: {
            patientProfile: {
                deletedAt: null
            }
        },
        select: {
            id: true,
            codeHash: true,
            status: true,
            lockedUntil: true,
            expiresAt: true,
            patientProfile: {
                select: {
                    id: true,
                    careCircleId: true,
                    displayName: true,
                    relationshipLabel: true,
                    status: true
                }
            }
        }
    });
    let matched;
    for (const candidate of candidates){
        if (await verifyArgon2id(input.code, candidate.codeHash)) matched = candidate;
    }
    if (!matched) {
        recordFailedLogin(attemptKey, now.getTime());
        throw new PatientAuthError("UNAUTHENTICATED");
    }
    const unavailable = matched.status !== "ACTIVE" || matched.patientProfile.status !== "ACTIVE" || matched.expiresAt !== null && matched.expiresAt <= now || matched.lockedUntil !== null && matched.lockedUntil > now;
    if (unavailable) {
        recordFailedLogin(attemptKey, now.getTime());
        throw new PatientAuthError("UNAUTHENTICATED");
    }
    loginAttempts.delete(attemptKey);
    const token = __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$crypto__$5b$external$5d$__$28$node$3a$crypto$2c$__cjs$29$__.randomBytes(32).toString("base64url");
    const expiresAt = new Date(now.getTime() + PATIENT_SESSION_MAX_AGE_SECONDS * 1_000);
    await db.$transaction(async (tx)=>{
        await tx.patientAccessCode.update({
            where: {
                id: matched.id
            },
            data: {
                failedAttemptCount: 0,
                lockedUntil: null,
                lastUsedAt: now
            }
        });
        await tx.patientSession.create({
            data: {
                patientProfileId: matched.patientProfile.id,
                tokenHash: sessionTokenHash(token, secret),
                expiresAt,
                lastSeenAt: now
            }
        });
        await tx.auditEvent.create({
            data: {
                careCircleId: matched.patientProfile.careCircleId,
                patientProfileId: matched.patientProfile.id,
                actorType: "PATIENT",
                actorPatientProfileId: matched.patientProfile.id,
                action: "PATIENT_LOGIN_SUCCEEDED",
                targetType: "PATIENT_SESSION",
                summary: "PATIENT_LOGIN_SUCCEEDED PATIENT_SESSION",
                requestId: input.requestId
            }
        });
    });
    return {
        token,
        expiresAt,
        context: {
            actorType: "PATIENT",
            patientProfile: {
                id: matched.patientProfile.id,
                displayName: matched.patientProfile.displayName,
                relationshipLabel: matched.patientProfile.relationshipLabel
            }
        }
    };
}
async function resolvePatientAuthContext(dependencies = {}) {
    const token = "token" in dependencies ? dependencies.token : await readPatientSessionCookie();
    if (!token) throw new PatientAuthError("UNAUTHENTICATED");
    const db = dependencies.db ?? (await __turbopack_context__.A("[project]/src/lib/db/client.ts [app-rsc] (ecmascript, async loader)")).prisma;
    const secret = dependencies.secret ?? (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getCoreServerEnv"])().PATIENT_SESSION_SECRET;
    const now = dependencies.now ?? new Date();
    const session = await db.patientSession.findUnique({
        where: {
            tokenHash: sessionTokenHash(token, secret)
        },
        select: {
            id: true,
            expiresAt: true,
            revokedAt: true,
            patientProfile: {
                select: {
                    id: true,
                    displayName: true,
                    relationshipLabel: true,
                    status: true,
                    deletedAt: true
                }
            }
        }
    });
    if (!session || session.revokedAt !== null || session.expiresAt <= now || session.patientProfile.status !== "ACTIVE" || session.patientProfile.deletedAt !== null) {
        throw new PatientAuthError("UNAUTHENTICATED");
    }
    await db.patientSession.updateMany({
        where: {
            id: session.id,
            revokedAt: null,
            expiresAt: {
                gt: now
            }
        },
        data: {
            lastSeenAt: now
        }
    });
    return {
        actorType: "PATIENT",
        patientProfile: {
            id: session.patientProfile.id,
            displayName: session.patientProfile.displayName,
            relationshipLabel: session.patientProfile.relationshipLabel
        }
    };
}
function requireBoundPatientProfile(context, patientProfileId) {
    if (context.patientProfile.id !== patientProfileId) {
        throw new PatientAuthError("FORBIDDEN");
    }
    return context;
}
async function revokePatientSession(dependencies = {}) {
    const token = "token" in dependencies ? dependencies.token : await readPatientSessionCookie();
    if (!token) return;
    const db = dependencies.db ?? (await __turbopack_context__.A("[project]/src/lib/db/client.ts [app-rsc] (ecmascript, async loader)")).prisma;
    const secret = dependencies.secret ?? (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$env$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getCoreServerEnv"])().PATIENT_SESSION_SECRET;
    await db.patientSession.updateMany({
        where: {
            tokenHash: sessionTokenHash(token, secret),
            revokedAt: null
        },
        data: {
            revokedAt: dependencies.now ?? new Date()
        }
    });
}
async function resolveAuthContext() {
    try {
        return await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$caregiver$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveCaregiverAuthContext"])();
    } catch (error) {
        if (!(error instanceof __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$caregiver$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CaregiverAuthError"]) || error.code !== "UNAUTHENTICATED") {
            throw error;
        }
    }
    return resolvePatientAuthContext();
}
}),
"[project]/src/app/caregiver/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>CaregiverPage,
    "dynamic",
    ()=>dynamic,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$ArrowLeft$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@phosphor-icons/react/dist/ssr/ArrowLeft.es.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$LockKey$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@phosphor-icons/react/dist/ssr/LockKey.es.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/app-dir/link.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$api$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/next/dist/api/navigation.react-server.js [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/components/navigation.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$auth$2f$caregiver$2d$auth$2d$panel$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/auth/caregiver-auth-panel.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$brand$2d$mark$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/brand-mark.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$patient$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/auth/patient.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
const metadata = {
    title: "Area Caregiver"
};
const dynamic = "force-dynamic";
async function CaregiverPage() {
    try {
        await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$patient$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolvePatientAuthContext"])();
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["redirect"])("/patient");
    } catch (error) {
        if (!(error instanceof __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$auth$2f$patient$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PatientAuthError"])) throw error;
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
        className: "production-caregiver-page",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("header", {
                className: "production-caregiver-header",
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$brand$2d$mark$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["BrandMark"], {
                        compact: true
                    }, void 0, false, {
                        fileName: "[project]/src/app/caregiver/page.tsx",
                        lineNumber: 25,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                        href: "/",
                        className: "caregiver-back-link",
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$ArrowLeft$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ArrowLeft"], {
                                size: 18,
                                weight: "bold",
                                "aria-hidden": "true"
                            }, void 0, false, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 26,
                                columnNumber: 56
                            }, this),
                            "Beranda"
                        ]
                    }, void 0, true, {
                        fileName: "[project]/src/app/caregiver/page.tsx",
                        lineNumber: 26,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/src/app/caregiver/page.tsx",
                lineNumber: 24,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                className: "production-caregiver-content",
                "aria-labelledby": "caregiver-title",
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                        className: "production-caregiver-heading",
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                                className: "section-kicker",
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {}, void 0, false, {
                                        fileName: "[project]/src/app/caregiver/page.tsx",
                                        lineNumber: 31,
                                        columnNumber: 44
                                    }, this),
                                    "Area Caregiver"
                                ]
                            }, void 0, true, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 31,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                                id: "caregiver-title",
                                children: "Konteks perawatan yang jelas, tanpa kebisingan."
                            }, void 0, false, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 32,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                children: "Masuk sebagai Owner atau Family Member. Sesi, Care Circle, dan peran selalu diverifikasi oleh server."
                            }, void 0, false, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 33,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/src/app/caregiver/page.tsx",
                        lineNumber: 30,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                        className: "production-caregiver-layout",
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$auth$2f$caregiver$2d$auth$2d$panel$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CaregiverAuthPanel"], {}, void 0, false, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 40,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("aside", {
                                className: "caregiver-security-note",
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$phosphor$2d$icons$2f$react$2f$dist$2f$ssr$2f$LockKey$2e$es$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LockKey"], {
                                        size: 24,
                                        weight: "bold",
                                        "aria-hidden": "true"
                                    }, void 0, false, {
                                        fileName: "[project]/src/app/caregiver/page.tsx",
                                        lineNumber: 42,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                        children: [
                                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("strong", {
                                                children: "Patient Profile tetap terisolasi"
                                            }, void 0, false, {
                                                fileName: "[project]/src/app/caregiver/page.tsx",
                                                lineNumber: 44,
                                                columnNumber: 15
                                            }, this),
                                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                                children: "Saat profile aktif diganti, konteks lama dibersihkan sebelum profile baru dimuat. Pilihan di layar bukan authorization."
                                            }, void 0, false, {
                                                fileName: "[project]/src/app/caregiver/page.tsx",
                                                lineNumber: 45,
                                                columnNumber: 15
                                            }, this)
                                        ]
                                    }, void 0, true, {
                                        fileName: "[project]/src/app/caregiver/page.tsx",
                                        lineNumber: 43,
                                        columnNumber: 13
                                    }, this)
                                ]
                            }, void 0, true, {
                                fileName: "[project]/src/app/caregiver/page.tsx",
                                lineNumber: 41,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/src/app/caregiver/page.tsx",
                        lineNumber: 39,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/src/app/caregiver/page.tsx",
                lineNumber: 29,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/src/app/caregiver/page.tsx",
        lineNumber: 23,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/caregiver/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/caregiver/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__1nifia0._.js.map