var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/auth/me/route.js")
R.c("server/chunks/[root-of-the-server]__1w04bq8._.js")
R.c("server/chunks/[root-of-the-server]__0rk6g5k._.js")
R.c("server/chunks/node_modules_next_09vsiz_._.js")
R.c("server/chunks/node_modules_zod_v4_1soyrv-._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00x2u05._.js")
R.c("server/chunks/[root-of-the-server]__09sf56r._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_auth_me_route_actions_0opdztq.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/auth/me/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/auth/me/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
