var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/patient-profiles/[patientProfileId]/dashboard/route.js")
R.c("server/chunks/[root-of-the-server]__18rnwve._.js")
R.c("server/chunks/[root-of-the-server]__1dl_sws._.js")
R.c("server/chunks/node_modules_next_11-q-pn._.js")
R.c("server/chunks/node_modules_zod_v4_1soyrv-._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00x2u05._.js")
R.c("server/chunks/[root-of-the-server]__09sf56r._.js")
R.c("server/chunks/1jng_app_api_v1_patient-profiles_[patientProfileId]_dashboard_route_actions_1xph8fh.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/patient-profiles/[patientProfileId]/dashboard/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/patient-profiles/[patientProfileId]/dashboard/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
