var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/bpjs-guides/route.js")
R.c("server/chunks/[root-of-the-server]__1fjj664._.js")
R.c("server/chunks/[root-of-the-server]__1--353c._.js")
R.c("server/chunks/node_modules_next_20aodyq._.js")
R.c("server/chunks/node_modules_zod_v4_1soyrv-._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00x2u05._.js")
R.c("server/chunks/[root-of-the-server]__09sf56r._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_bpjs-guides_route_actions_0y5coti.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/bpjs-guides/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/v1/bpjs-guides/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
