// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/caregiver" | "/caregiver/invite/[token]" | "/caregiver/register" | "/patient" | "/patient/login" | "/prototype/caregiver" | "/prototype/caregiver/chat" | "/prototype/caregiver/documents/review" | "/prototype/caregiver/documents/upload" | "/prototype/caregiver/facilities" | "/prototype/caregiver/sos" | "/prototype/patient/access" | "/prototype/patient/check-in" | "/prototype/patient/home" | "/prototype/patient/sos"
type AppRouteHandlerRoutes = "/api/v1/auth/me" | "/api/v1/auth/patient/login" | "/api/v1/auth/patient/logout" | "/api/v1/care-circle/invitations" | "/api/v1/care-circle/invitations/[token]" | "/api/v1/care-circle/invitations/[token]/accept" | "/api/v1/onboarding/owner" | "/api/v1/patient-profiles" | "/api/v1/patient-profiles/[patientProfileId]" | "/api/v1/patient-profiles/[patientProfileId]/access-code" | "/api/v1/patient-profiles/[patientProfileId]/check-ins" | "/api/v1/patient-profiles/[patientProfileId]/dashboard" | "/api/v1/patient-profiles/[patientProfileId]/deactivate" | "/api/v1/patient-profiles/[patientProfileId]/documents" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/complete" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/download-url" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extract" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/confirm" | "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/reject" | "/api/v1/patient-profiles/[patientProfileId]/documents/upload-intent" | "/api/v1/patient-profiles/[patientProfileId]/health-notes" | "/api/v1/patient-profiles/[patientProfileId]/medications" | "/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]" | "/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/logs" | "/api/v1/patient-profiles/[patientProfileId]/reminders" | "/api/v1/patient-profiles/[patientProfileId]/reminders/[reminderId]" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/auth/me": {}
  "/api/v1/auth/patient/login": {}
  "/api/v1/auth/patient/logout": {}
  "/api/v1/care-circle/invitations": {}
  "/api/v1/care-circle/invitations/[token]": { "token": string; }
  "/api/v1/care-circle/invitations/[token]/accept": { "token": string; }
  "/api/v1/onboarding/owner": {}
  "/api/v1/patient-profiles": {}
  "/api/v1/patient-profiles/[patientProfileId]": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/access-code": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/check-ins": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/dashboard": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/deactivate": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]": { "patientProfileId": string; "documentId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/complete": { "patientProfileId": string; "documentId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/download-url": { "patientProfileId": string; "documentId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extract": { "patientProfileId": string; "documentId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]": { "patientProfileId": string; "documentId": string; "extractionId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/confirm": { "patientProfileId": string; "documentId": string; "extractionId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/reject": { "patientProfileId": string; "documentId": string; "extractionId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/documents/upload-intent": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/health-notes": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/medications": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]": { "patientProfileId": string; "medicationId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/logs": { "patientProfileId": string; "medicationId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/reminders": { "patientProfileId": string; }
  "/api/v1/patient-profiles/[patientProfileId]/reminders/[reminderId]": { "patientProfileId": string; "reminderId": string; }
  "/auth/callback": {}
  "/caregiver": {}
  "/caregiver/invite/[token]": { "token": string; }
  "/caregiver/register": {}
  "/patient": {}
  "/patient/login": {}
  "/prototype/caregiver": {}
  "/prototype/caregiver/chat": {}
  "/prototype/caregiver/documents/review": {}
  "/prototype/caregiver/documents/upload": {}
  "/prototype/caregiver/facilities": {}
  "/prototype/caregiver/sos": {}
  "/prototype/patient/access": {}
  "/prototype/patient/check-in": {}
  "/prototype/patient/home": {}
  "/prototype/patient/sos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
