// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/caregiver/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/caregiver/invite/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/caregiver/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/caregiver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/caregiver">> = Specific
  const handler = {} as typeof import("../../../src/app/caregiver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/caregiver/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/caregiver/register">> = Specific
  const handler = {} as typeof import("../../../src/app/caregiver/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/patient/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/login">> = Specific
  const handler = {} as typeof import("../../../src/app/patient/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/patient/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../../src/app/patient/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/documents/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver/documents/review">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/documents/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/documents/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver/documents/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/documents/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/facilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver/facilities">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/facilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/caregiver/sos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/caregiver/sos">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/caregiver/sos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/patient/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/patient/access">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/patient/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/patient/check-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/patient/check-in">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/patient/check-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/patient/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/patient/home">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/patient/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prototype/patient/sos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototype/patient/sos">> = Specific
  const handler = {} as typeof import("../../../src/app/prototype/patient/sos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/patient/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/patient/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/patient/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/patient/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/patient/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/patient/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/care-circle/invitations/[token]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/care-circle/invitations/[token]/accept">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/care-circle/invitations/[token]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/care-circle/invitations/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/care-circle/invitations/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/care-circle/invitations/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/care-circle/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/care-circle/invitations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/care-circle/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/onboarding/owner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/onboarding/owner">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/onboarding/owner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/access-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/access-code">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/access-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/check-ins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/check-ins">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/check-ins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/deactivate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/complete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/download-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/download-url">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/download-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extract">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/reject">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/extractions/[extractionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/upload-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/documents/upload-intent">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/documents/upload-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/health-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/health-notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/health-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/[medicationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/medications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/medications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/reminders/[reminderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/reminders/[reminderId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/reminders/[reminderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]/reminders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/[patientProfileId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles/[patientProfileId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/[patientProfileId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/patient-profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/patient-profiles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/patient-profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
